### ISSUE TITLE
outdated dependencies

### ISSUE THREAD

**Issue by vmartynets** [auth0-samples/auth0-cordova-samples#13]
(AUTH-4231)
Sample uses outdated version of `@auth0/cordova`, `auth0-js` and other dependencies.

**Comment by JohnMcLear** [comment]
Ugh, wouldn't take much to fix this..  Wake up Auth0 crew! :)

**Comment by beardaway** [comment]
Hey Folks! 

Firstly sorry for such delay in response. We're trying to do our best in providing support to our developer community but sometimes it's just about people resources constraints so thanks for understanding.

I'll tackle it once I'm back from Xmas break! Thanks for pinging us!
