### ISSUE TITLE
how to import auth-0 and auth0-cordova without using webpack?

### ISSUE THREAD

**Issue by biswas123** [auth0-samples/auth0-cordova-samples#27]
how to import auth-0 and auth0-cordova without using webpack?

**Comment by Kelows** [comment]
you could try with my fork : https://github.com/Kelows/phonegap-auth0
add in your config.xml but be careful, set the url to match your tenant etc..
hope will help

**Comment by davidpatrick** [comment]
Thanks @Kelows for lending a hand here
