### ISSUE TITLE
Sample not working - leads to white blank screen (Android)

### ISSUE THREAD

**Issue by krthush** [auth0-samples/auth0-cordova-samples#37]
### Description

Followed basic Auth0 sample app instructions (shown below) and it leads to a blank screen.

### Expected behaviour

I would expect after following the auth0 instructions that I should have a basic cordova app which allows for login into my auth0 application.

### Actual behaviour 

Emulator stuck on white screen.

### Steps to reproduce the problem

Followed these exact instructions...

![image](https://user-images.githubusercontent.com/33790334/67090080-16705500-f1a1-11e9-86d2-3ff149c6fa05.png)

### Language / Framework Versions

Ran npm install -g such that most recent versions of NPM and Cordova were used.

### Testing environment

1. Windows 10
![image](https://user-images.githubusercontent.com/33790334/67090283-9d253200-f1a1-11e9-8561-f028543d2f31.png)
2. Android emulator running Android API Level 24 (Android 7.0) on a Pixel 2

### Screenshots

![image](https://user-images.githubusercontent.com/33790334/67090377-da89bf80-f1a1-11e9-81c0-50152bdba180.png)

**Comment by davidpatrick** [comment]
@krthush sorry for the delay on getting back to you on this.  This was previously maintained by the Auth0 Community, and now our SDKs team has taken over responsibility for this.

I experienced a similar issue on my machine  and followed these instructions to fix:
```
cd platforms/ios/cordova
npm install ios-sim@latest
cd ../../..
cordova run android --emulator
```

Let me know if you are still having this issue and need further help.  Until then I will close the issue seeing that this is reported some time ago.  I will re open if you are still experiencing issues.
