### ISSUE TITLE
Control does not return to redirect_uri when using Apple Sign in

### ISSUE THREAD

**Issue by yinzara** [auth0-samples/auth0-cordova-samples#38]
# Issue Report

When using this plugin with "Sign in With Apple" on an iPhone without biometrics or with a user that is not the primary user of the iPhone, panel does not redirect after signing in (ends up at a blank panel) making this plugin not function properly on the iPhone simulator and in some use cases on real iPhone devices when a user selects to sign in with a different user than the iPhone user.  

I believe this bug is either with Auth0 responses to the /login/callback redirect or a defect in the SFSafariViewController itself.

The behavior requires use of the iOS simulator or an iPhone, an Apple developers account, Auth0 tenant with Apple sign in configured appropriately, and an Application configured in Auth0 with access to the Apple sign in functionality.

I will provide more detailed information.

**Comment by Widcket** [comment]
Hi @yinzara, thanks for the report. I wasn't able to reproduce it with the [sample app](https://github.com/auth0-samples/auth0-cordova-samples):
![cordova-siwa-login](https://user-images.githubusercontent.com/5055789/75070763-aec17200-54d2-11ea-9828-6e75bd47ca62.gif)
Can you please try with that one?

**Comment by yinzara** [comment]
I actually opened the issue with full details now at:
https://github.com/auth0/auth0-cordova/issues/134
You can probably close this one in favor.
